:- object(cora_db, implements(cora_dbp)).

venue(class_7,venue_proceedings_26th_symposium_theory_computing_).
venue(class_8,venue_proceedings_twenty_sixth_symposium_theory_computing_).
author(class_7,author_blum_a_).
author(class_8,author_blum_a_).
title(class_7,title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_).
title(class_8,title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_).

haswordvenue(venue_proceedings_26th_symposium_theory_computing_,word_26th).
haswordvenue(venue_proceedings_26th_symposium_theory_computing_,word_pos).
haswordvenue(venue_proceedings_26th_symposium_theory_computing_,word_test).

haswordvenue(venue_proceedings_twenty_sixth_symposium_theory_computing_,word_pos).
haswordvenue(venue_proceedings_twenty_sixth_symposium_theory_computing_,word_sixth).
haswordvenue(venue_proceedings_twenty_sixth_symposium_theory_computing_,word_test).

haswordtitle(title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_,word_dnf).
haswordtitle(title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_,word_fourier).
haswordtitle(title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_,word_query).
haswordtitle(title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_,word_test).
haswordtitle(title_weakly_learning_learning_dnf_characterizing_statistical_query_using_fourier_analysis_,word_weakly).

haswordauthor(author_blum_a_,word_a).
haswordauthor(author_blum_a_,word_blum).

:- end_object.
